name: bts_commuterapp
description: A new flutter module project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    geolocator: ^5.1.4+2
    google_maps_flutter: ^0.5.21+8
    location: ^2.3.5
    # dio: ^3.0.4
    firebase_auth: ^0.14.0+5
    cloud_firestore: ^0.12.10+2
    # firebase_dynamic_links: ^0.5.0+1
    # rxdart: ^0.22.4
    # flutter_secure_storage: ^3.3.1+1
    # country_code_picker: ^1.1.7
    # pin_view: ^1.0.1
    # provider: ^3.1.0+1
    introduction_screen: ^1.0.7
    flutter_screenutil: ^0.6.0
    shared_preferences: ^0.5.4+5
    intl: ^0.16.0
    dio: ^3.0.5

  # cloud_firestore: ^0.12.9+5
  geoflutterfire: ^2.0.3+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section, 
  # like this:
  assets:
   - lib/assets/icon/icon.png
   - lib/assets/icon/icon-background.png
   - lib/assets/icon/bus-marker-blue.png
   - lib/assets/icon/bus-marker-green.png
   - lib/assets/icon/bus-marker-red.png
   - lib/assets/icon/bus-stop-balloon.png
   - lib/assets/map_style_day.txt
   - lib/assets/map_style_night.txt
   - lib/assets/icon/BTSLogo.png
   - lib/assets/images/1st.jpg
   - lib/assets/images/2nd.jpg
   - lib/assets/images/3rd.jpg
  #  - lib/assets/map_style_day.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.bts_commuterapp
    iosBundleIdentifier: com.example.btsCommuterapp
